# Generated by Django 4.2.3 on 2023-10-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_video_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dev_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
